### PR TITLE
fix(deps): upgrade i18next

### PR DESCRIPTION
**Pull request by dargmuesli**

### CODE REVIEW

**Comment by dargmuesli** [comment]
I recommend to set up [Renovate](https://github.com/marketplace/renovate).

**Comment by fwalzel** [comment]
Did this via Renovate.

**Comment by dargmuesli** [comment]
Ok, but why the `||` (or) and not just v20?
Also, projects that depend on yours need a new release of this project when there are updates to this project's dependencies to benefit from them too. I use [semantic release](https://github.com/semantic-release/semantic-release) to automate this too. If that's too much of a change for now, I'd return to asking for a new release by opening an issue from time to time ;D

**Comment by fwalzel** [comment]
Hello Jonas,

thank you for your contribution (and apologies for the delayed answer).

The || (or) was proposed by the Renovate Bot, which I accepted without much thinking. You’re right, it doesn’t make much sense (changed it already). 

Semantic release is a good idea, I shall think about that.
I’d be happy to hear further proposals for improvement from you.
 
Cheers,
Florian

**Comment by dargmuesli** [comment]
Hey, great to hear. I've created a proposal for semantic release usage as a PR for your convenience. As this is CI related stuff that I cannot test for this project currently, there is most likely further configuration to be done. I described that in detail over there at the PR. Have a good night!

**Pull request closed without merging**
